### ISSUE TITLE
Add varpro_lsqlinopts to optdmd varargin

### ISSUE THREAD

**Issue by ghost** [duqbo/optdmd#3]
Add option to insert linear constraints on eigenvalues to parent code. The attached is my attempt to do so - not sure if I messed up the other varargin etc. inequalities. Works for a simple case. (Sorry I'm not versed in pull, branch, merge)
[optdmd.m.zip](https://github.com/duqbo/optdmd/files/1985867/optdmd.m.zip)

Cheers,
Ben

**Comment by askhamwhat** [comment]
Hi Ben,
This looks like a reasonable way to do this. I'll add it in a new commit soon. Thanks!
Cheers,
Travis

**Comment by askhamwhat** [comment]
I've incorporated this along with a few other changes (I discovered there was a bug in the old version). The simple_example.m file shows usage, though it doesn't really make sense on that example.
