### ISSUE TITLE
Constrain minimum mode oscillation frequency?

### ISSUE THREAD

**Issue by ghost** [duqbo/optdmd#4]
Hi Travis,
This may not be possible, but I have been trying to think of a way to add a constraint to the minimum absolute value of the imaginary part of the eigenvalues. The motivation is to restrict the period of mode oscillation to less than the period of temporal data in X. Returned modes with longer periods are likely not particularly meaningful for primarily oscillatory data since the input data does not contain information about behavior at these slow frequencies. 

I have not been able to come up with a way to use the lsqlin inequalities (A x <= b, Aeq x = beq, lb <= x <= ub) to represent |x| > omega for the imaginary part.

Thanks for any advice, and no worries if this is not easily implementable.
Cheers,
Ben

**Comment by askhamwhat** [comment]
Hi Ben,

I think you're right that the lsqlin framework can't do this (how disappointing! I would have assumed it can). The lsqlin choice was basically an arbitrary one that I thought would encompass a number of constraints. I'll think about how to add something more generic as an option. 

The way constraints are currently handled isn't terribly sophisticated. At each step, I simply take the result of a step of Levenberg Marquardt and replace it with the nearest point satisfying the constraints. This would be easy to do with the constraint you describe. Will get back to you...

Cheers,
Travis

**Comment by askhamwhat** [comment]
I've added a feature to the optdmd where you can supply your own projection function. See the 7th example in simple_example.m 

For your constraint, the function

proxfun = @(alpha) real(alpha) + 1i*sign(imag(alpha)).*max(abs(imag(alpha)),omega);

should work

**Comment by ghost** [comment]
Wow thanks! That works perfectly and allows me to mess with all sorts of nonlinear constraints.
Cheers,
Ben

**Comment by askhamwhat** [comment]
Hi Ben,

I discussed this with a colleague and he pointed out that there's potential for danger here. Because the constraint corresponds to the union of some disjoint sets, it is unclear what performance guarantees (if any) exist. For instance, it seems that in many situations it would be impossible for an alpha to jump from a positive to negative imaginary part, even if a better minimum would result. Please keep this in mind. If you find that you need something that works better, we have a couple of ideas but they would require a more serious implementation effort.

Cheers,
Travis

**Comment by ghost** [comment]
Hi Travis,
First, thanks again for spending time to implement this.

I don't have anywhere close to the math experience to tell if what I'm
doing is good idea.

The datasets I am testing on always return sin/cos pair modes (one
negative, one positive imaginary part of eigenvalues). I hope this means
that keeping the eigenvalues from switching sign is not an issue.

For some context, I am using optDMD to pull out the oscillatory part of a
mean-subtracted flow field (the end goal is a triple decomposition of the
flow). Thus I have constrained the eigenvalues to have only imaginary
parts, with a minimum frequency. I suspect that the resulting modes are
equivalent to DFT modes, but this method allows for identification of an
'optimal' subset of frequencies (I hope).

Happy to chat further if this use of your algorithm is of interest.

Cheers,
Ben
